### ISSUE TITLE
Possibility to build with "--with-sdl"

### ISSUE THREAD

**Issue by ruifig** [JoshuaBrookover/bgfx.cmake#12]
I don't think it is possibly at the moment to set anything equivalent to bgfx's "--with-sdl" build parameter.

**Comment by JoshuaBrookover** [comment]
Yeah, that's missing. I will need to investigate a bit further into what that flag does exactly.

Also missing:
```
--with-glfw
--with-profiler
--with-scintilla
--with-shared-lib
```

**Comment by leokolln** [comment]
I've added the options to `examples.cmake` with pull request #25 

Please notice that I only tested it on Linux.
SDL on OS X may require further changes, see [CMake FindSDL](https://cmake.org/cmake/help/latest/module/FindSDL.html) documentation.

**Comment by JoshuaBrookover** [comment]
Closing, see PR #25 
Cheers @leokolln

**Comment by jaccen** [comment]
when can use on android ?

**Comment by JoshuaBrookover** [comment]
I don't know much about Android development, so, hard to say.
