### ISSUE TITLE
CXX_STANDARD 11 does not compile

### ISSUE THREAD

**Issue by tjysdsg** [JoshuaBrookover/bgfx.cmake#31]
Compilng on Ubuntu 18.04 LTS, with cmake minimum version 3.0, [The body of constexpr function not a return-statement](https://stackoverflow.com/questions/45097171/the-body-of-constexpr-function-not-a-return-statement)

After changing `CMakeLists.txt` in the `bgfx.cmake` root directory to this:

```
if (APPLE)
    set(CMAKE_CXX_FLAGS "-ObjC++ --std=c++14")
elseif (UNIX)
    set(CMAKE_CXX_STANDARD 14)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
endif ()
```

It compiles and runs great!

**Comment by TheComet** [comment]
Can confirm, this fixes compiling the newest versions of bgfx, bx, and bimg on linux.

**Comment by JoshuaBrookover** [comment]
If you can make a PR I'll merge it in, otherwise I will have this fixed after the holidays here in the US. Thanks!

**Comment by JoshuaBrookover** [comment]
Merged PR. Thanks so much!
