### ISSUE TITLE
mingw under macOS: build errors

### ISSUE THREAD

**Issue by djtracy** [JoshuaBrookover/bgfx.cmake#4]
Hello Joshua,

I am using macOS 10.11.6, and mingw-w64 installed via the excellent 'brew' package manager.

My MINGW environment var is set to '/usr/local/Cellar/mingw-w64/5.0.1', which contains a bin/ directory that has links to all of the tools.

Compiling using bgfx.cmake I get the following compile-time errors:

In file included from /Volumes/data/mine/SciFiGameProjects/third_party/bx/src/amalgamated.cpp:10:0:
/Volumes/data/mine/SciFiGameProjects/third_party/bx/src/debug.cpp: In function ‘void bx::debugPrintfData(const void*, uint32_t, const char*, ...)’:
/Volumes/data/mine/SciFiGameProjects/third_party/bx/src/debug.cpp:93:25: error: expected ‘)’ before ‘PRIxPTR’
 #define DBG_ADDRESS "%" PRIxPTR
                         ^
/Volumes/data/mine/SciFiGameProjects/third_party/bx/src/debug.cpp:106:26: note: in expansion of macro ‘DBG_ADDRESS’
   debugPrintf("\ndata: " DBG_ADDRESS ", size: %d\n", _data, _size);
                          ^~~~~~~~~~~
/Volumes/data/mine/SciFiGameProjects/third_party/bx/src/debug.cpp:93:25: error: expected ‘)’ before ‘PRIxPTR’
 #define DBG_ADDRESS "%" PRIxPTR
                         ^
/Volumes/data/mine/SciFiGameProjects/third_party/bx/src/debug.cpp:126:23: note: in expansion of macro ‘DBG_ADDRESS’
      debugPrintf("\t" DBG_ADDRESS "\t" HEX_DUMP_FORMAT "\t%s\n", data, hex, ascii);
                       ^~~~~~~~~~~
/Volumes/data/mine/SciFiGameProjects/third_party/bx/src/debug.cpp:93:25: error: expected ‘)’ before ‘PRIxPTR’
 #define DBG_ADDRESS "%" PRIxPTR
                         ^
/Volumes/data/mine/SciFiGameProjects/third_party/bx/src/debug.cpp:136:22: note: in expansion of macro ‘DBG_ADDRESS’
     debugPrintf("\t" DBG_ADDRESS "\t" HEX_DUMP_FORMAT "\t%s\n", data, hex, ascii);
                      ^~~~~~~~~~~

Note that my first order of business was to try this under bgfx's "native" GENie build system, in case the code base itself had trouble supporting this (somewhat obtuse?) build environment. The GENie build does have a problem (and I've filed an Issue), but GENie makes it to link stage, so it does not have this particular issue.

Notes:

1. The problem is that PRIxPTR is not defined (problem disappears when I throw the def in the file).
2. The macro definition of PRIxPTR should be in inttypes.h, but only the C99 version (not C++).
3. I have ./toolchain-x86_64/x86_64-w64-mingw32/include/inttypes.h in my environment, the C version that has this definition (confirmed).
4. I also have a C++ file version: ./toolchain-x86_64/x86_64-w64-mingw32/include/c++/6.3.0/tr1/inttypes.h. This file does not have the definition (not C99 conformant).
5. The target file (debug.cpp) is a C++ file. I do not know why this *should* (or shouldn't) work, but it seems to fail under MINGW on macOS.

I also had a problem with linking, which might manifest for MINGW targets on linux & macOS (any cross compile).

To correct the first problem on my end, I did a very hacky thing: copied definitions from mingw headers to cmake -D defines. You probably don't want to do that, but here a patch of my changes:

    diff --git a/cmake/bx.cmake b/cmake/bx.cmake
    index b5204b6..304908d 100644
    --- a/cmake/bx.cmake
    +++ b/cmake/bx.cmake
    @@ -21,7 +21,7 @@ file( GLOB BX_SOURCES ${BX_DIR}/src/*.cpp )
     add_library( bx STATIC ${BX_SOURCES} )

     # Link against psapi in Visual Studio
    -if( MSVC )
    +if( MSVC OR MINGW )
            target_link_libraries( bx PUBLIC psapi )
     endif()

    @@ -33,6 +33,10 @@ if( MSVC )
            target_include_directories( bx PUBLIC ${BX_DIR}/include/compat/msvc )
            target_compile_definitions( bx PUBLIC "__STDC_FORMAT_MACROS" )
     elseif( MINGW )
    +       add_definitions(-DPRIxPTR=\"I64x\")
    +       add_definitions(-DPRIx64=\"I64x\")
    +       add_definitions(-DPRIi64=\"I64i\")
    +       add_definitions(-DPRId64=\"I64d\")
            target_include_directories( bx PUBLIC ${BX_DIR}/include/compat/mingw )
     elseif( APPLE )
            target_include_directories( bx PUBLIC ${BX_DIR}/include/compat/osx )

Hopefully this is instructive on the problem. With this patch (and after linking the project to C & C++ libs statically), everything is honky dory for bgfx, bx, & my project. GENie's problem is presently unresolved, but I can use bgfx.cmake to complete builds in this environment.

I can also use wine to run my project & tests. So thanks to cmake's cross compilation support, I can build & run all of my targets (macOS, iOS, Win32, Android) on macOS!

**Comment by JoshuaBrookover** [comment]
Can you try copying that target_compile_definitions with __STDC_FORMAT_MACROS in the MSVC block into the MINGW block? Seems that's necessary in c++ environments.

https://sourceforge.net/p/mingw/mingw-org-wsl/ci/master/tree/include/inttypes.h#l44

Looking at bx's genie configuration it defines that under all platforms, along with a few others I should probably copy just in case.

https://github.com/bkaradzic/bx/blob/db5e1d9b8fcf0f76f3b236455420403a3e639357/scripts/toolchain.lua#L570

**Comment by djtracy** [comment]
That does indeed solve the problem. No hack-definitions necessary.

**Comment by JoshuaBrookover** [comment]
I believe the latest changes have fixed your issue. If not, we can reopen.
