### ISSUE TITLE
can't find example binary files

### ISSUE THREAD

**Issue by ohouha** [JoshuaBrookover/bgfx.cmake#46]
Hi,
I build whole project using cmake on ubuntu 16.04, but where can I find the example binary files? I just find geometryc shaderc texturec texturev binary files in the build folder.
Please help me.
Thanks.

**Comment by ohouha** [comment]
oh, nevermind, I found the in the cmakelist, should turn BGFX_INSTALL_EXAMPLES on.

**Comment by JoshuaBrookover** [comment]
Yeah, per the [discussion here](https://github.com/JoshuaBrookover/bgfx.cmake/issues/35), I think we'll turn that on by default.
