### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by NukeBird** [JoshuaBrookover/bgfx.cmake#47]
So, how things going with android support?

Can I somehow help with it?

**Comment by JoshuaBrookover** [comment]
As far as I know, no one is working on this. I don't have an Android phone to test with, nor have I done any Android development. PRs welcome, preferably ones that add a job to [our travis ci](https://travis-ci.org/JoshuaBrookover/bgfx.cmake) so we don't break it in the future.

**Comment by widberg** [comment]
I have merged #58 (Android support and CI) which fixed some of the cmake issues when trying to build for android, and added x86 and armeabiv7 builds to the Travis CI. I will leave this issue open for a little while longer to allow any further problems with android support to be addressed.
