### ISSUE TITLE
Amalgamated builds cause linking errors with tools. 

### ISSUE THREAD

**Issue by thedmd** [JoshuaBrookover/bgfx.cmake#6]
Tools use CMake interface library to include some files from bgfx sources. When using amalgamated build these sources are marked as headers and therefore not complied nor linked.

This can be solved by createing cpp file in binary directory that include necessary file there.

Changing header only flag to false in tool cmake file may not work due to how cmake works.

Thanks for your work. : )

**Comment by JoshuaBrookover** [comment]
You're right. That's a weird case. Neat idea with the cpp file, let me think on it a bit.

**Comment by JoshuaBrookover** [comment]
I fixed this using the approach you suggested. Thank you!

https://github.com/JoshuaBrookover/bgfx.cmake/commit/87759f1c11daf024bfb97ee4c46e062371ebc04d
